baseURL = "https://netsplit.uk"
languageCode = "en-gb"
title = "netsplit"
theme = "terminal"

paginate = 5

[params]
    description = "Software development and systems engineering"
    contentTypeName = "post"
    themeColor = "green"
    showMenuItems = 2
    showLanguageSelector = false
    fullWidthTheme = true
    centerTheme = false
    enableGitInfo = true
    showLastUpdated = true

[languages]
    [languages.en]
        languageName = "English"
        title = "netsplit"
        subtitle = ""
        owner = ""
        keywords = ""
        copyright = ""
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"
        missingContentMessage = "Page not found"
        missingBackButtonLabel = "Back to homepage"

        [languages.en.params.logo]
            logoText = "netsplit"
            logoHomeLink = "/"

