baseURL = "https://netsplit.uk"
languageCode = "en-gb"
title = "netsplit"
theme = "mike"

paginate = 8

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'trac'
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files

[params]
  description = "Software development and systems engineering"
  copyrightStartYear = 2010
